# Automatically generate a pre-release when changes land on master
# https://github.com/marvinpinto/action-automatic-releases
# This example workflow will kick in as soon as changes land on master. After running the steps to build and test your project:

# It will create (or replace) a git tag called latest.
# Generate a changelog from all the commits between this, and the previous latest tag.
# Generate a new release associated with the latest tag (removing any previous associated releases).
# Update this new release with the specified title (e.g. Development Build).
# Upload LICENSE.txt and any jar files as release assets.
# Mark this release as a pre-release.

name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar